//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostsFileEditor.Properties {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HostsFileEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ArchiveExists {
            get {
                return ResourceManager.GetString("ArchiveExists", resourceCulture);
            }
        }
        
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        internal static string hosts {
            get {
                return ResourceManager.GetString("hosts", resourceCulture);
            }
        }
        
        internal static string InputArchivePrompt {
            get {
                return ResourceManager.GetString("InputArchivePrompt", resourceCulture);
            }
        }
        
        internal static string InvalidHostEntries {
            get {
                return ResourceManager.GetString("InvalidHostEntries", resourceCulture);
            }
        }
        
        internal static string InvalidHostnames {
            get {
                return ResourceManager.GetString("InvalidHostnames", resourceCulture);
            }
        }
        
        internal static string InvalidIPAddress {
            get {
                return ResourceManager.GetString("InvalidIPAddress", resourceCulture);
            }
        }
        
        internal static string LoseChangesDialogCaption {
            get {
                return ResourceManager.GetString("LoseChangesDialogCaption", resourceCulture);
            }
        }
        
        internal static string LoseChangesQuestion {
            get {
                return ResourceManager.GetString("LoseChangesQuestion", resourceCulture);
            }
        }
        
        internal static string PingFailed {
            get {
                return ResourceManager.GetString("PingFailed", resourceCulture);
            }
        }
        
        internal static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
    }
}
